distributed_type: DEEPSPEED
mixed_precision: "bf16"
downcast_bf16: 'no'
deepspeed_config:
  bf16:
    enabled: "auto"
  optimizer:
    type: "AdamW"
    params:
      lr: "auto"
      betas: "auto"
      eps: "auto"
      weight_decay: "auto"
  scheduler:
    type: "WarmupLR"
    params:
      warmup_min_lr: 1.0e-06
      warmup_max_lr: 1.0e-05
      warmup_num_steps: 50
  zero_optimization:
    stage: 2
    offload_optimizer:
      device: "none"
      pin_memory: true
    allgather_partitions: true
    allgather_bucket_size: "auto"
    overlap_comm: true
    reduce_scatter: true
    reduce_bucket_size: "auto"
    contiguous_gradients: true
  gradient_accumulation_steps: 4
  gradient_clipping: "auto"
  steps_per_print: "auto"
  train_batch_size: "auto"
  train_micro_batch_size_per_gpu: "auto"
  wall_clock_breakdown: false
  deepspeed_multinode_launcher: "standard"